// Every human-readable sequential code in this app (EOS-###, QT-###, TKT-###,
// EXP-###, PO-###, AMC-###) is generated by counting existing rows and adding
// one — but the count-then-insert isn't atomic, so two concurrent requests can
// read the same count and both try to insert the same code, which throws a
// Prisma P2002 unique-constraint error (the column is genuinely globally
// unique — see the comments at each call site; scoping the count per-org
// would just reintroduce the cross-org collisions fixed in commit 6afe280).
//
// withUniqueCodeRetry re-runs `attempt` (which should recompute the count and
// code fresh each time, then perform the insert) whenever it fails with a
// unique-constraint violation, so the retry naturally picks the next free
// number instead of colliding again.
function isUniqueConstraintError(err: unknown): boolean {
  return err instanceof Error && "code" in err && (err as { code?: string }).code === "P2002";
}

export async function withUniqueCodeRetry<T>(
  attempt: () => Promise<T>,
  maxAttempts = 5
): Promise<T> {
  let lastError: unknown;
  for (let i = 0; i < maxAttempts; i++) {
    try {
      return await attempt();
    } catch (err) {
      if (!isUniqueConstraintError(err)) throw err;
      lastError = err;
    }
  }
  throw lastError;
}
